INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'normal', 'normal'),
    (UUID(), 'fighting', 'fighting'),
    (UUID(), 'flying', 'flying'),
    (UUID(), 'poison', 'poison'),
    (UUID(), 'ground', 'ground'),
    (UUID(), 'rock', 'rock'),
    (UUID(), 'bug', 'bug'),
    (UUID(), 'ghost', 'ghost'),
    (UUID(), 'steel', 'steel'),
    (UUID(), 'fire', 'fire'),
    (UUID(), 'water', 'water'),
    (UUID(), 'grass', 'grass'),
    (UUID(), 'electric', 'electric'),
    (UUID(), 'psychic', 'psychic'),
    (UUID(), 'ice', 'ice'),
    (UUID(), 'dragon', 'dragon'),
    (UUID(), 'dark', 'dark'),
    (UUID(), 'fairy', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'flying', 'normal'),
    (UUID(), 'flying', 'fighting'),
    (UUID(), 'flying', 'poison'),
    (UUID(), 'flying', 'ground'),
    (UUID(), 'flying', 'rock'),
    (UUID(), 'flying', 'bug'),
    (UUID(), 'flying', 'ghost'),
    (UUID(), 'flying', 'steel'),
    (UUID(), 'flying', 'fire'),
    (UUID(), 'flying', 'water'),
    (UUID(), 'flying', 'grass'),
    (UUID(), 'flying', 'electric'),
    (UUID(), 'flying', 'psychic'),
    (UUID(), 'flying', 'ice'),
    (UUID(), 'flying', 'dragon'),
    (UUID(), 'flying', 'dark'),
    (UUID(), 'flying', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'normal', 'fighting'),
    (UUID(), 'normal', 'flying'),
    (UUID(), 'normal', 'poison'),
    (UUID(), 'normal', 'ground'),
    (UUID(), 'normal', 'rock'),
    (UUID(), 'normal', 'bug'),
    (UUID(), 'normal', 'ghost'),
    (UUID(), 'normal', 'steel'),
    (UUID(), 'normal', 'fire'),
    (UUID(), 'normal', 'water'),
    (UUID(), 'normal', 'grass'),
    (UUID(), 'normal', 'electric'),
    (UUID(), 'normal', 'psychic'),
    (UUID(), 'normal', 'ice'),
    (UUID(), 'normal', 'dragon'),
    (UUID(), 'normal', 'dark'),
    (UUID(), 'normal', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'fighting', 'normal'),
    (UUID(), 'fighting', 'flying'),
    (UUID(), 'fighting', 'poison'),
    (UUID(), 'fighting', 'ground'),
    (UUID(), 'fighting', 'rock'),
    (UUID(), 'fighting', 'bug'),
    (UUID(), 'fighting', 'ghost'),
    (UUID(), 'fighting', 'steel'),
    (UUID(), 'fighting', 'fire'),
    (UUID(), 'fighting', 'water'),
    (UUID(), 'fighting', 'grass'),
    (UUID(), 'fighting', 'electric'),
    (UUID(), 'fighting', 'psychic'),
    (UUID(), 'fighting', 'ice'),
    (UUID(), 'fighting', 'dragon'),
    (UUID(), 'fighting', 'dark'),
    (UUID(), 'fighting', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'poison', 'normal'),
    (UUID(), 'poison', 'fighting'),
    (UUID(), 'poison', 'flying'),
    (UUID(), 'poison', 'ground'),
    (UUID(), 'poison', 'rock'),
    (UUID(), 'poison', 'bug'),
    (UUID(), 'poison', 'ghost'),
    (UUID(), 'poison', 'steel'),
    (UUID(), 'poison', 'fire'),
    (UUID(), 'poison', 'water'),
    (UUID(), 'poison', 'grass'),
    (UUID(), 'poison', 'electric'),
    (UUID(), 'poison', 'psychic'),
    (UUID(), 'poison', 'ice'),
    (UUID(), 'poison', 'dragon'),
    (UUID(), 'poison', 'dark'),
    (UUID(), 'poison', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'ground', 'normal'),
    (UUID(), 'ground', 'fighting'),
    (UUID(), 'ground', 'flying'),
    (UUID(), 'ground', 'poison'),
    (UUID(), 'ground', 'rock'),
    (UUID(), 'ground', 'bug'),
    (UUID(), 'ground', 'ghost'),
    (UUID(), 'ground', 'steel'),
    (UUID(), 'ground', 'fire'),
    (UUID(), 'ground', 'water'),
    (UUID(), 'ground', 'grass'),
    (UUID(), 'ground', 'electric'),
    (UUID(), 'ground', 'psychic'),
    (UUID(), 'ground', 'ice'),
    (UUID(), 'ground', 'dragon'),
    (UUID(), 'ground', 'dark'),
    (UUID(), 'ground', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'rock', 'normal'),
    (UUID(), 'rock', 'fighting'),
    (UUID(), 'rock', 'flying'),
    (UUID(), 'rock', 'poison'),
    (UUID(), 'rock', 'ground'),
    (UUID(), 'rock', 'rock'),
    (UUID(), 'rock', 'bug'),
    (UUID(), 'rock', 'ghost'),
    (UUID(), 'rock', 'steel'),
    (UUID(), 'rock', 'fire'),
    (UUID(), 'rock', 'water'),
    (UUID(), 'rock', 'grass'),
    (UUID(), 'rock', 'electric'),
    (UUID(), 'rock', 'psychic'),
    (UUID(), 'rock', 'ice'),
    (UUID(), 'rock', 'dragon'),
    (UUID(), 'rock', 'dark'),
    (UUID(), 'rock', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'bug', 'normal'),
    (UUID(), 'bug', 'fighting'),
    (UUID(), 'bug', 'flying'),
    (UUID(), 'bug', 'poison'),
    (UUID(), 'bug', 'ground'),
    (UUID(), 'bug', 'rock'),
    (UUID(), 'bug', 'ghost'),
    (UUID(), 'bug', 'steel'),
    (UUID(), 'bug', 'fire'),
    (UUID(), 'bug', 'water'),
    (UUID(), 'bug', 'grass'),
    (UUID(), 'bug', 'electric'),
    (UUID(), 'bug', 'psychic'),
    (UUID(), 'bug', 'ice'),
    (UUID(), 'bug', 'dragon'),
    (UUID(), 'bug', 'dark'),
    (UUID(), 'bug', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'ghost', 'normal'),
    (UUID(), 'ghost', 'fighting'),
    (UUID(), 'ghost', 'flying'),
    (UUID(), 'ghost', 'poison'),
    (UUID(), 'ghost', 'ground'),
    (UUID(), 'ghost', 'rock'),
    (UUID(), 'ghost', 'bug'),
    (UUID(), 'ghost', 'steel'),
    (UUID(), 'ghost', 'fire'),
    (UUID(), 'ghost', 'water'),
    (UUID(), 'ghost', 'grass'),
    (UUID(), 'ghost', 'electric'),
    (UUID(), 'ghost', 'psychic'),
    (UUID(), 'ghost', 'ice'),
    (UUID(), 'ghost', 'dragon'),
    (UUID(), 'ghost', 'dark'),
    (UUID(), 'ghost', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'steel', 'normal'),
    (UUID(), 'steel', 'fighting'),
    (UUID(), 'steel', 'flying'),
    (UUID(), 'steel', 'poison'),
    (UUID(), 'steel', 'ground'),
    (UUID(), 'steel', 'rock'),
    (UUID(), 'steel', 'bug'),
    (UUID(), 'steel', 'ghost'),
    (UUID(), 'steel', 'fire'),
    (UUID(), 'steel', 'water'),
    (UUID(), 'steel', 'grass'),
    (UUID(), 'steel', 'electric'),
    (UUID(), 'steel', 'psychic'),
    (UUID(), 'steel', 'ice'),
    (UUID(), 'steel', 'dragon'),
    (UUID(), 'steel', 'dark'),
    (UUID(), 'steel', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'fire', 'normal'),
    (UUID(), 'fire', 'fighting'),
    (UUID(), 'fire', 'flying'),
    (UUID(), 'fire', 'poison'),
    (UUID(), 'fire', 'ground'),
    (UUID(), 'fire', 'rock'),
    (UUID(), 'fire', 'bug'),
    (UUID(), 'fire', 'ghost'),
    (UUID(), 'fire', 'steel'),
    (UUID(), 'fire', 'water'),
    (UUID(), 'fire', 'grass'),
    (UUID(), 'fire', 'electric'),
    (UUID(), 'fire', 'psychic'),
    (UUID(), 'fire', 'ice'),
    (UUID(), 'fire', 'dragon'),
    (UUID(), 'fire', 'dark'),
    (UUID(), 'fire', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'water', 'normal'),
    (UUID(), 'water', 'fighting'),
    (UUID(), 'water', 'flying'),
    (UUID(), 'water', 'poison'),
    (UUID(), 'water', 'ground'),
    (UUID(), 'water', 'rock'),
    (UUID(), 'water', 'bug'),
    (UUID(), 'water', 'ghost'),
    (UUID(), 'water', 'steel'),
    (UUID(), 'water', 'fire'),
    (UUID(), 'water', 'grass'),
    (UUID(), 'water', 'electric'),
    (UUID(), 'water', 'psychic'),
    (UUID(), 'water', 'ice'),
    (UUID(), 'water', 'dragon'),
    (UUID(), 'water', 'dark'),
    (UUID(), 'water', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'grass', 'normal'),
    (UUID(), 'grass', 'fighting'),
    (UUID(), 'grass', 'flying'),
    (UUID(), 'grass', 'poison'),
    (UUID(), 'grass', 'ground'),
    (UUID(), 'grass', 'rock'),
    (UUID(), 'grass', 'bug'),
    (UUID(), 'grass', 'ghost'),
    (UUID(), 'grass', 'steel'),
    (UUID(), 'grass', 'fire'),
    (UUID(), 'grass', 'water'),
    (UUID(), 'grass', 'electric'),
    (UUID(), 'grass', 'psychic'),
    (UUID(), 'grass', 'ice'),
    (UUID(), 'grass', 'dragon'),
    (UUID(), 'grass', 'dark'),
    (UUID(), 'grass', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'electric', 'normal'),
    (UUID(), 'electric', 'fighting'),
    (UUID(), 'electric', 'flying'),
    (UUID(), 'electric', 'poison'),
    (UUID(), 'electric', 'ground'),
    (UUID(), 'electric', 'rock'),
    (UUID(), 'electric', 'bug'),
    (UUID(), 'electric', 'ghost'),
    (UUID(), 'electric', 'steel'),
    (UUID(), 'electric', 'fire'),
    (UUID(), 'electric', 'water'),
    (UUID(), 'electric', 'grass'),
    (UUID(), 'electric', 'psychic'),
    (UUID(), 'electric', 'ice'),
    (UUID(), 'electric', 'dragon'),
    (UUID(), 'electric', 'dark'),
    (UUID(), 'electric', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'psychic', 'normal'),
    (UUID(), 'psychic', 'fighting'),
    (UUID(), 'psychic', 'flying'),
    (UUID(), 'psychic', 'poison'),
    (UUID(), 'psychic', 'ground'),
    (UUID(), 'psychic', 'rock'),
    (UUID(), 'psychic', 'bug'),
    (UUID(), 'psychic', 'ghost'),
    (UUID(), 'psychic', 'steel'),
    (UUID(), 'psychic', 'fire'),
    (UUID(), 'psychic', 'water'),
    (UUID(), 'psychic', 'grass'),
    (UUID(), 'psychic', 'electric'),
    (UUID(), 'psychic', 'ice'),
    (UUID(), 'psychic', 'dragon'),
    (UUID(), 'psychic', 'dark'),
    (UUID(), 'psychic', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'ice', 'normal'),
    (UUID(), 'ice', 'fighting'),
    (UUID(), 'ice', 'flying'),
    (UUID(), 'ice', 'poison'),
    (UUID(), 'ice', 'ground'),
    (UUID(), 'ice', 'rock'),
    (UUID(), 'ice', 'bug'),
    (UUID(), 'ice', 'ghost'),
    (UUID(), 'ice', 'steel'),
    (UUID(), 'ice', 'fire'),
    (UUID(), 'ice', 'water'),
    (UUID(), 'ice', 'grass'),
    (UUID(), 'ice', 'electric'),
    (UUID(), 'ice', 'psychic'),
    (UUID(), 'ice', 'dragon'),
    (UUID(), 'ice', 'dark'),
    (UUID(), 'ice', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'dragon', 'normal'),
    (UUID(), 'dragon', 'fighting'),
    (UUID(), 'dragon', 'flying'),
    (UUID(), 'dragon', 'poison'),
    (UUID(), 'dragon', 'ground'),
    (UUID(), 'dragon', 'rock'),
    (UUID(), 'dragon', 'bug'),
    (UUID(), 'dragon', 'ghost'),
    (UUID(), 'dragon', 'steel'),
    (UUID(), 'dragon', 'fire'),
    (UUID(), 'dragon', 'water'),
    (UUID(), 'dragon', 'grass'),
    (UUID(), 'dragon', 'electric'),
    (UUID(), 'dragon', 'psychic'),
    (UUID(), 'dragon', 'ice'),
    (UUID(), 'dragon', 'dark'),
    (UUID(), 'dragon', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'dark', 'normal'),
    (UUID(), 'dark', 'fighting'),
    (UUID(), 'dark', 'flying'),
    (UUID(), 'dark', 'poison'),
    (UUID(), 'dark', 'ground'),
    (UUID(), 'dark', 'rock'),
    (UUID(), 'dark', 'bug'),
    (UUID(), 'dark', 'ghost'),
    (UUID(), 'dark', 'steel'),
    (UUID(), 'dark', 'fire'),
    (UUID(), 'dark', 'water'),
    (UUID(), 'dark', 'grass'),
    (UUID(), 'dark', 'electric'),
    (UUID(), 'dark', 'psychic'),
    (UUID(), 'dark', 'ice'),
    (UUID(), 'dark', 'dragon'),
    (UUID(), 'dark', 'fairy');

INSERT INTO type (type_id, type1, type2) VALUES
    (UUID(), 'fairy', 'normal'),
    (UUID(), 'fairy', 'fighting'),
    (UUID(), 'fairy', 'flying'),
    (UUID(), 'fairy', 'poison'),
    (UUID(), 'fairy', 'ground'),
    (UUID(), 'fairy', 'rock'),
    (UUID(), 'fairy', 'bug'),
    (UUID(), 'fairy', 'ghost'),
    (UUID(), 'fairy', 'steel'),
    (UUID(), 'fairy', 'fire'),
    (UUID(), 'fairy', 'water'),
    (UUID(), 'fairy', 'grass'),
    (UUID(), 'fairy', 'electric'),
    (UUID(), 'fairy', 'psychic'),
    (UUID(), 'fairy', 'ice'),
    (UUID(), 'fairy', 'dragon'),
    (UUID(), 'fairy', 'dark');

SELECT * FROM type;