INSERT INTO ability (ability_id , name, effect) VALUES
    (UUID(), 'Adaptability', 'Powers up moves of the same type.'),
    (UUID(), 'Aerilate', 'Turns Normal-type moves into Flying-type moves.'),
    (UUID(), 'Aftermath', 'Damages the attacker landing the finishing hit.'),
    (UUID(), 'Air Lock', 'Eliminates the effects of weather.'),
    (UUID(), 'Analytic', 'Boosts move power when the Pokémon moves last.'),
    (UUID(), 'Anger Point', 'Maxes Attack after taking a critical hit.'),
    (UUID(), 'Anger Shell', 'Lowers Defense/Sp. Def and raises Attack/Sp. Atk/Speed when HP drops below half.'),
    (UUID(), 'Anticipation', 'Senses a foe''s dangerous moves.'),
    (UUID(), 'Arena Trap', 'Prevents the foe from fleeing.'),
    (UUID(), 'Armor Tail', 'Prevents opponent using priority moves.'),
    (UUID(), 'Aroma Veil', 'Protects allies from attacks that limit their move choices.'),
    (UUID(), 'As One', 'Combines Unnerve and Chilling Neigh/Grim Neigh'),
    (UUID(), 'Aura Break', 'Reduces power of Dark- and Fairy-type moves.'),
    (UUID(), 'Bad Dreams', 'Reduces a sleeping foe''s HP.'),
    (UUID(), 'Ball Fetch', 'Retrieves a Poké Ball from a failed throw.'),
    (UUID(), 'Battery', 'Raises power of teammates'' Special moves.'),
    (UUID(), 'Battle Armor', 'The Pokémon is protected against critical hits.'),
    (UUID(), 'Battle Bond', 'Transform into Ash-Greninja after causing opponent to faint.'),
    (UUID(), 'Beads of Ruin', 'Lowers Special Defense of all Pokémon except itself.'),
    (UUID(), 'Beast Boost', 'The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.'),
    (UUID(), 'Berserk', 'Raises Special Attack when HP drops below half.'),
    (UUID(), 'Big Pecks', 'Protects the Pokémon from Defense-lowering attacks.'),
    (UUID(), 'Blaze', 'Powers up Fire-type moves in a pinch.'),
    (UUID(), 'Bulletproof', 'Protects the Pokémon from ball and bomb moves.'),
    (UUID(), 'Cheek Pouch', 'Restores additional HP when a Berry is consumed.'),
    (UUID(), 'Chilling Neigh', 'Boosts Attack after knocking out a Pokémon.'),
    (UUID(), 'Chlorophyll', 'Boosts the Pokémon''s Speed in sunshine.'),
    (UUID(), 'Clear Body', 'Prevents other Pokémon from lowering its stats.'),
    (UUID(), 'Cloud Nine', 'Eliminates the effects of weather.'),
    (UUID(), 'Color Change', 'Changes the Pokémon''s type to the foe''s move.'),
    (UUID(), 'Comatose', 'The Pokémon is always asleep but can still attack.'),
    (UUID(), 'Commander', 'Goes inside the mouth of an ally Dondozo if one is on the field.'),
    (UUID(), 'Competitive', 'Sharply raises Special Attack when the Pokémon''s stats are lowered.'),
    (UUID(), 'Compound Eyes', 'The Pokémon''s accuracy is boosted.'),
    (UUID(), 'Contrary', 'Makes stat changes have an opposite effect.'),
    (UUID(), 'Corrosion', 'The Pokémon can poison Steel and Poison types.'),
    (UUID(), 'Costar', 'Copies ally''s stat changes on entering battle.'),
    (UUID(), 'Cotton Down', 'Lowers foe''s Speed when hit.'),
    (UUID(), 'Cud Chew', 'Can eat the same Berry twice.'),
    (UUID(), 'Curious Medicine', 'Resets all stat changes upon entering battlefield.'),
    (UUID(), 'Cursed Body', 'May disable a move used on the Pokémon.'),
    (UUID(), 'Cute Charm', 'Contact with the Pokémon may cause infatuation.'),
    (UUID(), 'Damp', 'Prevents the use of self-destructing moves.'),
    (UUID(), 'Dancer', 'Copies the foe''s Dance moves.'),
    (UUID(), 'Dark Aura', 'Raises power of Dark type moves for all Pokémon in battle.'),
    (UUID(), 'Dauntless Shield', 'Boosts Defense in battle.'),
    (UUID(), 'Dazzling', 'Protects the Pokémon from high-priority moves.'),
    (UUID(), 'Defeatist', 'Lowers stats when HP drops below half.'),
    (UUID(), 'Defiant', 'Sharply raises Attack when the Pokémon''s stats are lowered.'),
    (UUID(), 'Delta Stream', 'Creates strong winds when the ability activates.'),
    (UUID(), 'Desolate Land', 'Turns the sunlight extremely harsh when the ability activates.'),
    (UUID(), 'Disguise', 'Avoids damage for one turn.'),
    (UUID(), 'Download', 'Adjusts power according to a foe''s defenses.'),
    (UUID(), 'Dragon''s Maw', 'Powers up Dragon-type moves.'),
    (UUID(), 'Drizzle', 'The Pokémon makes it rain when it enters a battle.'),
    (UUID(), 'Drought', 'Turns the sunlight harsh when the Pokémon enters a battle.'),
    (UUID(), 'Dry Skin', 'Reduces HP if it is hot. Water restores HP.'),
    (UUID(), 'Early Bird', 'The Pokémon awakens quickly from sleep.'),
    (UUID(), 'Earth Eater', 'Restores HP when hit by a Ground-type move.'),
    (UUID(), 'Effect Spore', 'Contact may poison or cause paralysis or sleep.'),
    (UUID(), 'Electric Surge', 'The Pokémon creates an Electric Terrain when it enters a battle.'),
    (UUID(), 'Electromorphosis', 'Doubles power of the next Electric-type move when hit by an attack.'),
    (UUID(), 'Embody Aspect', 'Boosts Attack/Defense/Sp. Def/Speed depending on the form.'),
    (UUID(), 'Emergency Exit', 'Switches out when HP falls below 50%.'),
    (UUID(), 'Fairy Aura', 'Raises power of Fairy type moves for all Pokémon in battle.'),
    (UUID(), 'Filter', 'Reduces damage from super-effective attacks.'),
    (UUID(), 'Flame Body', 'Contact with the Pokémon may burn the attacker.'),
    (UUID(), 'Flare Boost', 'Powers up special attacks when burned.'),
    (UUID(), 'Flash Fire', 'It powers up Fire-type moves if it''s hit by one.'),
    (UUID(), 'Flower Gift', 'Powers up party Pokémon when it is sunny.'),
    (UUID(), 'Flower Veil', 'Prevents lowering of ally Grass-type Pokémon''s stats.'),
    (UUID(), 'Fluffy', 'Halves damage from contact moves, but doubles damage from Fire-type moves.'),
    (UUID(), 'Forecast', 'Castform transforms with the weather.'),
    (UUID(), 'Forewarn', 'Determines what moves a foe has.'),
    (UUID(), 'Friend Guard', 'Reduces damage done to allies.'),
    (UUID(), 'Frisk', 'The Pokémon can check a foe''s held item.'),
    (UUID(), 'Full Metal Body', 'Prevents other Pokémon from lowering its stats.'),
    (UUID(), 'Fur Coat', 'Reduces damage from physical moves.'),
    (UUID(), 'Gale Wings', 'Gives priority to Flying-type moves.'),
    (UUID(), 'Galvanize', 'Normal-type moves become Electric-type moves and their power boosted.'),
    (UUID(), 'Gluttony', 'Encourages the early use of a held Berry.'),
    (UUID(), 'Good as Gold', 'Gives immunity to status moves.'),
    (UUID(), 'Gooey', 'Contact with the Pokémon lowers the attacker''s Speed stat.'),
    (UUID(), 'Gorilla Tactics', 'Boosts the Pokémon''s Attack stat but only allows the use of the first selected move.'),
    (UUID(), 'Gulp Missile', 'Swallowing the Gigantamax energy, the Pokémon moves to the next turn and attacks.'),
    (UUID(), 'Guts', 'Boosts Attack if there is a status problem.'),
    (UUID(), 'Harvest', 'May create another Berry after one is used.'),
    (UUID(), 'Healer', 'Sometimes heals an ally''s status condition.'),
    (UUID(), 'Heatproof', 'Weakens the power of Fire-type moves.'),
    (UUID(), 'Heavy Metal', 'Doubles the Pokémon''s weight.'),
    (UUID(), 'Honey Gather', 'The Pokémon may gather Honey from somewhere.'),
    (UUID(), 'Huge Power', 'Raises the Pokémon''s Attack stat.'),
    (UUID(), 'Hunger Switch', 'Changes form and type based on time.'),
    (UUID(), 'Hustle', 'Boosts the Attack stat but lowers accuracy.'),
    (UUID(), 'Hydration', 'Heals status conditions if it is raining.'),
    (UUID(), 'Hyper Cutter', 'Prevents the Attack stat from being lowered.'),
    (UUID(), 'Ice Body', 'The Pokémon regains HP in a hailstorm.'),
    (UUID(), 'Ice Scales', 'Halves the damage taken from special moves.'),
    (UUID(), 'Iceface', 'Damages the attacker landing the finishing hit.'),
    (UUID(), 'Illuminate', 'Raises the likelihood of meeting wild Pokémon.'),
    (UUID(), 'Illusion', 'Comes out disguised as the Pokémon in the party''s last spot.'),
    (UUID(), 'Immunity', 'Prevents the Pokémon from getting poisoned.'),
    (UUID(), 'Imposter', 'Transforms upon entering battle.'),
    (UUID(), 'Infiltrator', 'Passes through the foe''s barrier and strikes.'),
    (UUID(), 'Inner Focus', 'The Pokémon is protected from flinching.'),
    (UUID(), 'Insomnia', 'Prevents the Pokémon from falling asleep.'),
    (UUID(), 'Intimidate', 'Lowers the opposing Pokémon''s Attack stat.'),
    (UUID(), 'Intrepid Sword', 'Boosts Attack in battle.'),
    (UUID(), 'Iron Barbs', 'Inflicts damage to the attacker on contact with iron barbs.'),
    (UUID(), 'Iron Fist', 'Boosts the power of punching moves.'),
    (UUID(), 'Justified', 'Raises Attack when hit by a Dark-type move.'),
    (UUID(), 'Keen Eye', 'Keeps the Pokémon from losing accuracy.'),
    (UUID(), 'Klutz', 'The Pokémon can''t use any held items.'),
    (UUID(), 'Leaf Guard', 'Prevents status conditions in sunny weather.'),
    (UUID(), 'Levitate', 'Gives full immunity to all Ground-type moves.'),
    (UUID(), 'Libero', 'Changes the Pokémon''s type to the type of the move it''s about to use.'),
    (UUID(), 'Light Metal', 'Halves the Pokémon''s weight.'),
    (UUID(), 'Lightning Rod', 'The Pokémon draws in all Electric-type moves.'),
    (UUID(), 'Limber', 'The Pokémon is protected from paralysis.'),
    (UUID(), 'Liquid Voice', 'All sound-based moves become Water type.'),
    (UUID(), 'Long Reach', 'The Pokémon uses its moves without making contact with the target.'),
    (UUID(), 'Magic Bounce', 'Reflects status moves, instead of getting hit by them.'),
    (UUID(), 'Magic Guard', 'The Pokémon only takes damage from attacks.'),
    (UUID(), 'Magician', 'The Pokémon steals the held item of a Pokémon it hits with a move.'),
    (UUID(), 'Magma Armor', 'Prevents the Pokémon from becoming frozen.'),
    (UUID(), 'Magnet Pull', 'Prevents Steel-type Pokémon from escaping.'),
    (UUID(), 'Marvel Scale', 'Boosts Defense if there is a status problem.'),
    (UUID(), 'Mega Launcher', 'Powers up aura and pulse moves.'),
    (UUID(), 'Merciless', 'The Pokémon''s attacks become critical hits if the target is poisoned.'),
    (UUID(), 'Mimicry', 'Changes type depending on location.'),
    (UUID(), 'Minus', 'Boosts Sp. Atk if another Pokémon has Plus.'),
    (UUID(), 'Mirror Armor', 'Bounces back only stat-lowering effects.'),
    (UUID(), 'Misty Surge', 'Creates a misty terrain when the Pokémon enters a battle.'),
    (UUID(), 'Mold Breaker', 'Moves can be used regardless of Abilities.'),
    (UUID(), 'Moody', 'Raises one stat sharply and lowers another every turn.'),
    (UUID(), 'Motor Drive', 'Raises Speed if hit by an Electric-type move.'),
    (UUID(), 'Moxie', 'Boosts Attack after knocking out any Pokémon.'),
    (UUID(), 'Multiscale', 'Reduces damage when HP is full.'),
    (UUID(), 'Multitype', 'Changes type to match the held Plate or Z-Crystal.'),
    (UUID(), 'Mummy', 'Contact with the Pokémon changes the attacker''s Ability.'),
    (UUID(), 'Natural Cure', 'All status problems are healed upon switching out.'),
    (UUID(), 'Neuroforce', 'Boosts power of super effective moves.'),
    (UUID(), 'Neutralizing Gas', 'Nullifies the effects of all other Abilities.'),
    (UUID(), 'No Guard', 'Ensures attacks by or against the Pokémon land.'),
    (UUID(), 'Normalize', 'All the Pokémon''s moves become Normal type.'),
    (UUID(), 'Oblivious', 'Prevents the Pokémon from becoming infatuated.'),
    (UUID(), 'Overcoat', 'Protects the Pokémon from things like sand, hail, and powder.'),
    (UUID(), 'Overgrow', 'Powers up Grass-type moves in a pinch.'),
    (UUID(), 'Own Tempo', 'Prevents the Pokémon from becoming confused.'),
    (UUID(), 'Parental Bond', 'Allows the Pokémon to attack twice.'),
    (UUID(), 'Pastel Veil', 'Protects the Pokémon and its ally from being poisoned.'),
    (UUID(), 'Perish Body', 'When hit by a move, the Pokémon and the attacker faint after three turns.'),
    (UUID(), 'Pickpocket', 'Steals an item when hit by another Pokémon.'),
    (UUID(), 'Pickup', 'The Pokémon may pick up items.'),
    (UUID(), 'Pixilate', 'Turns Normal-type moves into Fairy-type moves.'),
    (UUID(), 'Plus', 'Boosts Sp. Atk if another Pokémon has Minus.'),
    (UUID(), 'Poison Heal', 'Restores HP if the Pokémon is poisoned.'),
    (UUID(), 'Poison Point', 'Contact with the Pokémon may poison the attacker.'),
    (UUID(), 'Poison Touch', 'May poison targets when a Pokémon makes contact.'),
    (UUID(), 'Power Construct', 'Changes the Pokémon''s form when HP is half or less.'),
    (UUID(), 'Power Spot', 'Powers up allies'' moves.'),
    (UUID(), 'Power of Alchemy', 'The Pokémon copies the Ability of a defeated ally.'),
    (UUID(), 'Prankster', 'Gives priority to a status move.'),
    (UUID(), 'Pressure', 'The Pokémon raises opposing Pokémon''s PP usage.'),
    (UUID(), 'Primordial Sea', 'Makes the Pokémon and its allies immune to Fire-type moves.'),
    (UUID(), 'Prism Armor', 'Reduces damage from super effective attacks.'),
    (UUID(), 'Propeller Tail', 'Ignores effects of opposing Pokémon''s moves and Abilities that draw in moves.'),
    (UUID(), 'Protean', 'Changes the Pokémon''s type to the type of the move it just used.'),
    (UUID(), 'Psychic Surge', 'The Pokémon creates a Psychic Terrain when it enters a battle.'),
    (UUID(), 'Punk Rock', 'Boosts sound-based moves.'),
    (UUID(), 'Pure Power', 'Boosts the Pokémon''s Attack stat.'),
    (UUID(), 'Queenly Majesty', 'Protects the Pokémon and its allies from priority moves.'),
    (UUID(), 'Quick Draw', 'Boosts the Pokémon''s Speed stat and makes it move first occasionally.'),
    (UUID(), 'Quick Feet', 'Boosts Speed if there is a status problem.'),
    (UUID(), 'Rain Dish', 'The Pokémon gradually recovers HP in rain.'),
    (UUID(), 'Rattled', 'Boosts Speed if hit by a Bug-, Ghost-, or Dark-type move.'),
    (UUID(), 'Receiver', 'The Pokémon copies the Ability of a defeated ally.'),
    (UUID(), 'Reckless', 'Powers up moves that have recoil damage.'),
    (UUID(), 'Refrigerate', 'Turns Normal-type moves into Ice-type moves.'),
    (UUID(), 'Regenerator', 'Restores a little HP when withdrawn from battle.'),
    (UUID(), 'Ripen', 'Ripens Berries and doubles their effect.'),
    (UUID(), 'Rivalry', 'Deals more damage to Pokémon of the same gender.'),
    (UUID(), 'Rock Head', 'Protects the Pokémon from recoil damage.'),
    (UUID(), 'Rough Skin', 'Inflicts damage to the attacker on contact with rough skin.'),
    (UUID(), 'Run Away', 'Enables a sure getaway from wild Pokémon.'),
    (UUID(), 'Sand Force', 'Boosts certain moves'' power in a sandstorm.'),
    (UUID(), 'Sand Rush', 'Boosts the Pokémon''s Speed stat in a sandstorm.'),
    (UUID(), 'Sand Spit', 'Creates a sandstorm when hit by an attack.'),
    (UUID(), 'Sand Stream', 'The Pokémon summons a sandstorm in battle.'),
    (UUID(), 'Sand Veil', 'Boosts the Pokémon''s evasion in a sandstorm.'),
    (UUID(), 'Sap Sipper', 'Boosts Attack when hit by a Grass-type move.'),
    (UUID(), 'Schooling', 'Changes to School Form when at a high level.'),
    (UUID(), 'Scrappy', 'Enables moves to hit Ghost-type Pokémon.'),
    (UUID(), 'Screen Cleaner', 'Removes the effects of Light Screen, Reflect, and Aurora Veil from the opposing field when the Pokémon enters battle.'),
    (UUID(), 'Serene Grace', 'Boosts the likelihood of added effects appearing.'),
    (UUID(), 'Shadow Shield', 'Reduces damage when HP is full.'),
    (UUID(), 'Shadow Tag', 'Prevents the foe from escaping.'),
    (UUID(), 'Shed Skin', 'The Pokémon may heal its own status conditions.'),
    (UUID(), 'Sheer Force', 'Strengthens moves with extra effects to 130% of normal power, but the additional effects are ignored.'),
    (UUID(), 'Shell Armor', 'The Pokémon is protected against critical hits.'),
    (UUID(), 'Shield Dust', 'Blocks the added effects of attacks taken.'),
    (UUID(), 'Shields Down', 'The Pokémon forms a protective barrier when its HP becomes half or less.'),
    (UUID(), 'Simple', 'The Pokémon is prone to wild stat changes.'),
    (UUID(), 'Skill Link', 'Increases the frequency of multi-strike moves.'),
    (UUID(), 'Slow Start', 'Temporarily halves Attack and Speed stats.'),
    (UUID(), 'Slush Rush', 'Boosts the Pokémon''s Speed stat in a hailstorm.'),
    (UUID(), 'Sniper', 'Powers up moves if they become critical hits when attacking.'),
    (UUID(), 'Snow Cloak', 'Boosts evasion in a hailstorm.'),
    (UUID(), 'Snow Warning', 'The Pokémon summons a hailstorm when it enters a battle.'),
    (UUID(), 'Solar Power', 'Boosts Sp. Atk, but lowers HP in sunshine.'),
    (UUID(), 'Soul-Heart', 'Boosts its Sp. Atk stat every time a Pokémon faints.'),
    (UUID(), 'Soundproof', 'Gives full immunity to all sound-based moves.'),
    (UUID(), 'Speed Boost', 'Boosts the Speed stat each turn.'),
    (UUID(), 'Stakeout', 'Doubles the damage dealt to the target''s replacement if it switched out this turn.'),
    (UUID(), 'Stall', 'The Pokémon moves after all other Pokémon do.'),
    (UUID(), 'Stalwart', 'Ignores the effects of opposing Pokémon''s Abilities and moves that draw in moves.'),
    (UUID(), 'Stamina', 'Raises Defense when hit.'),
    (UUID(), 'Stance Change', 'The Pokémon changes form depending on how it battles.'),
    (UUID(), 'Static', 'Contact with the Pokémon may cause paralysis.'),
    (UUID(), 'Steadfast', 'Boosts Speed each time the Pokémon flinches.'),
    (UUID(), 'Steam Engine', 'Boosts the Pokémon''s Speed stat drastically if hit by a Fire- or Water-type move.'),
    (UUID(), 'Steelworker', 'Powers up Steel-type moves.'),
    (UUID(), 'Steely Spirit', 'Powers up ally Pokémon''s Steel-type moves.'),
    (UUID(), 'Stench', 'The stench may cause the target to flinch.'),
    (UUID(), 'Sticky Hold', 'Protects the Pokémon from item theft.'),
    (UUID(), 'Storm Drain', 'Draws in all Water-type moves to up Sp. Attack.'),
    (UUID(), 'Strong Jaw', 'Boosts the power of biting moves.'),
    (UUID(), 'Sturdy', 'It cannot be knocked out with one hit.'),
    (UUID(), 'Suction Cups', 'Negates moves that force switching out.'),
    (UUID(), 'Super Luck', 'Heightens the critical-hit ratios of moves.'),
    (UUID(), 'Surge Surfer', 'Doubles the Pokémon''s Speed stat on Electric Terrain.'),
    (UUID(), 'Swarm', 'Powers up Bug-type moves when the Pokémon''s HP is low.'),
    (UUID(), 'Sweet Veil', 'Prevents itself and ally Pokémon from falling asleep.'),
    (UUID(), 'Swift Swim', 'Boosts the Pokémon''s Speed stat in rain.'),
    (UUID(), 'Symbiosis', 'The Pokémon can pass an item to an ally.'),
    (UUID(), 'Synchronize', 'Passes on a burn, poison, or paralysis to the foe.'),
    (UUID(), 'Tangling Hair', 'Contact with the Pokémon lowers the attacker''s Speed stat.'),
    (UUID(), 'Tangled Feet', 'Raises evasion if the Pokémon is confused.'),
    (UUID(), 'Technician', 'Powers up the Pokémon''s weaker moves.'),
    (UUID(), 'Telepathy', 'Anticipates an ally''s attack and dodges it.'),
    (UUID(), 'Teravolt', 'Moves can be used regardless of Abilities.'),
    (UUID(), 'Thick Fat', 'Boosts resistance to Fire and Ice moves.'),
    (UUID(), 'Tinted Lens', 'Powers up “not very effective” moves.'),
    (UUID(), 'Torrent', 'Powers up Water-type moves in a pinch.'),
    (UUID(), 'Tough Claws', 'Boosts the power of contact moves.'),
    (UUID(), 'Toxic Boost', 'Powers up physical attacks when poisoned.'),
    (UUID(), 'Trace', 'The Pokémon copies the opponent''s Ability.'),
    (UUID(), 'Transistor', 'Powers up Electric-type moves.'),
    (UUID(), 'Triage', 'Gives priority to restorative moves.'),
    (UUID(), 'Truant', 'The Pokémon can''t use a move the turn following one where it used a move.'),
    (UUID(), 'Turboblaze', 'Moves can be used regardless of Abilities.'),
    (UUID(), 'Unaware', 'Ignores any stat changes in the Pokémon by the opponent.'),
    (UUID(), 'Unburden', 'Boosts the Speed stat if its held item is used or lost.'),
    (UUID(), 'Unnerve', 'Prevents opposing Pokémon from eating held Berries.'),
    (UUID(), 'Unseen Fist', 'Moves can hit Pokémon even if they protect themselves.'),
    (UUID(), 'Victory Star', 'Boosts the accuracy of its allies and itself.'),
    (UUID(), 'Vital Spirit', 'Prevents the Pokémon from falling asleep.'),
    (UUID(), 'Volt Absorb', 'Restores HP if hit by an Electric-type move.'),
    (UUID(), 'Wandering Spirit', 'The Pokémon exchanges Abilities with a Pokémon that hits it with a move that makes direct contact.'),
    (UUID(), 'Water Absorb', 'Restores HP if hit by a Water-type move.'),
    (UUID(), 'Water Bubble', 'Lowers the power of Fire-type moves done to the Pokémon and prevents the Pokémon from getting a burn.'),
    (UUID(), 'Water Compaction', 'Boosts the Pokémon''s Defense stat sharply when hit by a Water-type move.'),
    (UUID(), 'Water Veil', 'Prevents the Pokémon from getting a burn.'),
    (UUID(), 'Weak Armor', 'Raises Speed but lowers Defense when hit by a physical move.'),
    (UUID(), 'White Smoke', 'Prevents the Pokémon''s stats from being lowered by other Pokémon.'),
    (UUID(), 'Wimp Out', 'The Pokémon cowardly switches out when its HP becomes half or less.'),
    (UUID(), 'Wonder Guard', 'The Pokémon only takes damage from attacks that are super effective.'),
    (UUID(), 'Wonder Skin', 'Makes status-changing moves more likely to miss.'),
    (UUID(), 'Zen Mode', 'Changes the Pokémon''s shape when HP is halved.'),
    (UUID(), 'Zero to Hero', 'Transforms into its Hero Form when switching out.');

SELECT * FROM ability;